# Generated by Django 5.0.6 on 2024-05-12 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_managementorder_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rawmaterialstock',
            name='stok_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.stock'),
        ),
    ]
